Sumup reconciliation
SHRUBComms/murakami pull request #74
Opened 2024-10-29 08:43 UTC by rossporteous118

2024-11-05 20:48 UTC, jbsmith-git commented
Hi Ross, I'm just starting to take a look at your pull request. A couple of initial questions:
- Did you create the table using a sequelize migration? If not it might be worth adding a migration file in now?
- Did you try / get anywhere with making transaction_id a foreign key on the transactions table?

2024-11-12 20:50 UTC, pkeyss requested changes

2024-11-12 20:50 UTC, pkeyss commented on app/controllers/automated-scripts/backfill-transactions.js
> +const specifiedDate = new Date("2024-11-01");
Can we backfill from the last filled transaction or when the job last ran?

2024-11-12 20:50 UTC, pkeyss commented on app/controllers/automated-scripts/backfill-transactions.js
> +    if (now.toISOString().slice(0, 10) !== specifiedDate.toISOString().slice(0, 10)) {
Can we use `moment` here for readability please?

2024-11-12 20:50 UTC, pkeyss commented on app/controllers/automated-scripts/reconcile-transactions.js
Can we unify this with the backfill so that the behaviour is that we get the most recent sumup transaction from the database, and fill forwards from there (and also handle the case where there are no existing sumup transactions in the database)?

It would also be good to figure out what happens if a sumup transaction is refunded and whether we would handle it sensibly. Does sumup post a refund transaction or update the status?

2024-11-14 09:35 UTC, rossporteous118 commented
To answer your guys points:

1.  The table was created with a sequelize migration but I haven't began relating the SumUp transactions to the internal transactions tables yet. 

2. My goal right now was just to make sure that the backfill method is capable of saving all previous SumUp transactions to the table. If this is successful, the reconciliation method will run each day following the backfill and download new transactions. The backfill will run on a specified date but I am not sure when it would be best to run this?

3. We should be able to handle refunds sensibly. Each SumUp transaction has a 'type' attribute' which is either 'PAYMENT' or 'REFUND'. We could check for refund type either in the Murakami reconciliation or with SQL queries after the data has been saved to the table and handle this appropriately.

2024-12-15 19:21 UTC, pkeyss approved these changes

2024-12-15 19:22 UTC, SHRUBComms approved these changes

2024-12-15 19:22 UTC, merged